import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import React from "react";
import Navbar from "./Components/Navbar";
import Hero from "./Components/Hero";
import Works from "./Components/Works";
import Impact from "./Components/Impact";
import Featured from "./Components/Featured";
import Testimonial from "./Components/Testimonial";
import Transparency from "./Components/Transparency";
import Vision from "./Components/Vision";
import Faq from "./Components/Faqs";
import Footer from "./Components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <Hero />
        <Works/>
        <Impact />
        <Featured/>
        <Testimonial/>
        <Transparency />
        <Vision />
        <Faq />
        <Footer />
       
      </body>
    </html>
  );
}
